sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
before_script:
  - yarn --ignore-engines
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
branches:
  only:
    - master
    - /^greenkeeper/.*$/